from datetime import datetime
from fastapi import APIRouter, HTTPException, Request, status


router = APIRouter()

@router.post("/aliases")
async def generate_aliases(
	request: Request,
	domain: str = "addy.io2hme",
	description: str = "Generated by addy.io2hme",
):
	"""Generates an email alias"""

	label = domain
	hme = request.app.state.hme

	generated = await hme.generate_email()
	print("Generated:", generated)
	if not generated["success"]:
		raise HTTPException(
			status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
			detail=generated["error"]["errorMessage"],
		)

	email = generated["result"]["hme"]

	reserved = await hme.reserve_email(email, label, description)
	print("Reserved:", reserved)
	if not reserved["success"]:
		raise HTTPException(
			status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
			detail=reserved["error"]["errorMessage"],
		)

	id = reserved["result"]["hme"]["anonymousId"]
	email_parts = email.split("@")
	created_at = datetime.fromtimestamp(generated["timestamp"])
	updated_at = datetime.fromtimestamp(reserved["timestamp"])

	return {
		"data": {
			"id": id,
			"user_id": None,
			"aliasable_id": None,
			"aliasable_type": None,
			"local_part": email_parts[0],
			"extension": None,
			"domain": email_parts[1],
			"email": email,
			"active": True,
			"custom_shared_domain": False,
			"description": description,
			"form_name": None,
			"attached_recipients_only": False,
			"email_forwarded": 0,
			"email_blocked": 0,
			"email_replied": 0,
			"email_sent": 0,
			"recipients": [],
			"last_forwarded": None,
			"last_blocked": None,
			"last_replied": None,
			"last_sent": None,
			"created_at": created_at,
			"updated_at": updated_at,
			"deleted_at": None,
		},
		"hme": {
			"generated": generated,
			"reserved": reserved,
		},
	}
